version: "3.9"

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
    networks:
      - wp

  # Web server
  wordpress:
    ports:
      - "4000:80"
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes: ["./html:/var/www/html:delegated"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: secret
    networks:
      - wp

networks:
  wp:

volumes:
  db_data:
